---
fixes:
  - |
    Fixed an issue where calling :meth:`rustworkx.PyDiGraph.successor_indices`
    or :meth:`rustworkx.PyDiGraph.predecessor_indices` would raise a
    ``RuntimeError`` exception if they were called in a context where rustworkx
    is already working with a reference to a :class:`~rustworkx.PyDiGraph`
    (primarily if it were called in a callback function for another
    :class:`~rustworkx.PyDiGraph` method).
